# Generated by Django 3.2.11 on 2022-01-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
        migrations.RenameField(
            model_name='video',
            old_name='Slug',
            new_name='slug',
        ),
    ]
