# Generated by Django 3.2.11 on 2022-01-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20220112_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published Videos', 'verbose_name_plural': 'Published Videos'},
        ),
    ]
